@startuml

class CleaningTask <<aggregate>> {
  +taskId: int
  +description: string
  +status: string
  +points: int
  +Products: List<Products>
  +CleaningTask: List<CleaningTask>
  +Zeitstempel: Zeitstempel
  --
  +CleaningTask(string description, string status, int points, Products products)
  +RemoveProduct(Products p) 
  +ProductQuantity() : int
  +AddEmployee(employee: Employee)
  +RemoveEmployee(employee: Employee)
  +EmployeeQuantity() : int 
}

class DailyCleaningTask extends CleaningTask {
  +Priority: int
  --
  +tryHandIn(employee: Employee)
  +reviewHandIn() : boolean
}

class WeeklyCleaningTask extends CleaningTask {
  +PreferredDaY: string
  +Week: int
  +Year: int
  --
  +tryHandIn(employee: Employee)
  +reviewHandIn() : boolean
}

class Employee {
  +EmployeeId: int
  +Firstname: string
  +Lastname: string
  +Position: string
  +ActiveTasks: List<CleaningTask>
  +Employee: List<Employee>
  --
  +Employee(string firstname, string lastname, string position)
  +getActiveTasks() : List<CleaningTask>
  +CleaningTasksQuantity(): int
}

class Zeitstempel <<value object>>{
    +date: DateTime
    +description: string?
    +duration: int
}


class Products {
  + Id: int
  + Name: string
  + Description: string
  + ExpirationDate: DateTime
  --
  + Products(string name, Description description, date ExpireDate)
}

class Room {
  +RoomNumber: int
  +Beds: int
  +IsSmoking: boolean
  +CleaningTask: List<CleaningTask>
  --
  +Room(int beds, bool smoking, int points)
  +Points: int
  +AddCleaningTask(task: CleaningTask)
  +RemoveCleaningTask(CleaningTask task)
}

class Hotel <<aggregate>> {
  +Id: int
  +Guid: Guid
  +Name: string
  +Address: string
  +Rooms: List<Room>
  +Reservation: List<Reservation>
  --
  +Hotel(string n, string a)
  +AddRoom(Room r)
  +RemoveRoom(Room r)
  +RoomQuantity() : int
  +calculateAveragePoints() : int
  +AddReservation(Room room, DateTime checkInDate, DateTime checkOutDate)
  +removeReservation(Reservation reservation)
}

class Guest {
  +GuestId: int
  +Firstname: string
  +Lastname: string
  +Address: string
  +Reservation: Reservation
  --
  +Guest(string firstname, string lastname, string address, DateTime birthday, Reservation reservation)
}

class Reservation {
  +reservationId: int
  +room: Room
  +checkInDate: DateTime
  +checkOutDate: DateTime
  +guest: Guest
  +Reservation: List<Reservation>
  --
  +Reservation(Room room, DateTime checkInDate, DateTime checkOutDate, Guest guest)
}

DailyCleaningTask *--> Zeitstempel
WeeklyCleaningTask *--> Zeitstempel

Employee *--> CleaningTask
Room --> DailyCleaningTask
Room --> WeeklyCleaningTask
Room *--> Hotel
Reservation *--> Guest
Reservation --> Room
Products *--> CleaningTask

@enduml